#!/bin/bash

# Script to build a working webwork2 docker image.
#
# HOW TO RUN:
# to install the two dependencies from local filesystem, this needs to be run
# from a parent directory, which you should create. And then run this script
# from there. e.g.:
#
# mkdir webwork2-docker
# mv webwork2 webwork2-docker
# cd webwork2-docker
# ./webwork2/docker-build.sh v99
#
# Note this will not checkout/pull MathJax or PG if the directories already
# exist. If so, that's up to you.

set -eo pipefail

BUILD_VERSION_TAG=$1

if [ -d .git/ ]; then
  echo "This script should not be run from the webwork2/ directory. It should be run from one level up. See instructions."
  exit 1
fi

if [ "$BUILD_VERSION_TAG" == "" ]; then
  echo "specifiy build version tag as first arg: ./docker-build v99"
  exit 1
fi

# This probably won't matter unless you are not following the procedure outline
# above for some reason
WEBWORK2_GIT_URL=https://github.com/Edfinity/webwork2.git
WEBWORK2_BRANCH=edfinity-docker

# Set URL and branch of pg repository to use
PG_GIT_URL=https://github.com/Edfinity/pg.git
PG_BRANCH=master

if [ ! -d webwork2/ ]; then
  echo "Cloning branch $WEBWORK2_BRANCH branch from $WEBWORK2_GIT_URL"
  git clone --single-branch --branch ${WEBWORK2_BRANCH} --depth 1 $WEBWORK2_GIT_URL
fi
if [ ! -d pg/ ]; then
  echo "Cloning branch $PG_BRANCH branch from $PG_GIT_URL"
  git clone --single-branch --branch ${PG_BRANCH} --depth 1 $PG_GIT_URL
fi
if [ ! -d MathJax/ ]; then
  echo "Cloning MathJax"
  git clone --single-branch --branch legacy-v2 --depth 1 https://github.com/mathjax/MathJax
fi

docker build -t edfinity/webwork2:$BUILD_VERSION_TAG --platform linux/amd64 -f webwork2/Dockerfile .
