#!/bin/bash

# Build a working webwork2 docker image.
#
# HOW TO RUN:
# To install the two dependencies from local filesystem, this needs to be run
# from a parent directory, which you should create. And then run this script
# from there. e.g.:
#
# mkdir webwork2-docker
# mv webwork2 webwork2-docker
# cd webwork2-docker
# ./webwork2/docker-build -p -v v99
#
# Note this will not checkout/pull MathJax or PG if the directories already
# exist. If so, that's up to you.

set -eo pipefail

usage() {
  echo "Usage: ./webwork2/docker-build [options]"
  echo
  echo "Options:"
  echo "  -h           Print this help"
  echo "  -c           Clear the docker cache before building"
  echo "  -p           Push to AWS ECR"
  echo "  -V           Show all output while building"
  echo "  -v VERSION   Build version (required)"
  exit 1
}

CLEAR_CACHE=""
PUSH=false
VERBOSE=""
VERSION=""

while getopts "hcpVv:" opt; do
  case $opt in
    h) usage ;;
    c) CLEAR_CACHE="--no-cache" ;;
    p) PUSH=true ;;
    V) VERBOSE="--progress=plain" ;;
    v) VERSION="$OPTARG" ;;
    *) usage ;;
  esac
done

if [[ -z "$VERSION" ]]; then
  echo "You'll need to supply a build version (-v VERSION)"
  exit 1
fi

clone_if_needed() {
  local repo=$1 branch=$2 url=$3
  if [[ ! -d "$repo" ]]; then
    echo "Cloning branch $branch from $url"
    git clone --single-branch --branch "$branch" --depth 1 "$url"
  fi
}

clone_if_needed webwork2 edfinity-docker https://github.com/Edfinity/webwork2.git
clone_if_needed pg       master          https://github.com/Edfinity/pg.git
clone_if_needed MathJax  legacy-v2       https://github.com/mathjax/MathJax

REGION="us-east-1"
ACCT_ID=778618701612
TAG="$ACCT_ID.dkr.ecr.$REGION.amazonaws.com/webwork2:$VERSION"

echo "Building $TAG"
finch build $VERBOSE -t "$TAG" $CLEAR_CACHE --platform linux/amd64 -f webwork2/Dockerfile .

if [[ "$PUSH" == true ]]; then
  aws --profile edfinity ecr get-login-password --region "$REGION" \
    | finch login --username AWS --password-stdin "$ACCT_ID.dkr.ecr.$REGION.amazonaws.com"
  echo "Pushing $TAG"
  finch push "$TAG"
fi

finch history "$TAG"
