#!/usr/bin/env ruby

# Script to build a working webwork2 docker image.
#
# HOW TO RUN:
# to install the two dependencies from local filesystem, this needs to be run
# from a parent directory, which you should create. And then run this script
# from there. e.g.:
#
# mkdir webwork2-docker
# mv webwork2 webwork2-docker
# cd webwork2-docker
# ./webwork2/docker-build -p -v v99
#
# Note this will not checkout/pull MathJax or PG if the directories already
# exist. If so, that's up to you.

require 'optparse'

if ARGV.empty?
  puts "You'll need some args. Try '-h'."
  exit
end

options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: build [options]"

  opts.on('-h', '--help', 'Print this') do
    puts opts
    exit
  end

  opts.on('-c', '--clear-cache', 'Clear the docker cache before building') do
    options[:clear_cache] = "--no-cache"
  end

  opts.on('-p', '--push', 'Push to AWS ECR') do
    options[:push] = true
  end

  opts.on('-v', '--version VERSION', 'Build version') do |v|
    options[:version] = v
  end
end.parse!

if options[:version].nil?
  puts "You'll need to supply a build version"
  exit
end

def clone_if_needed(repo, branch, url)
  return if Dir.exists?(repo)

  puts "Cloning branch #{branch} branch from #{url}"
  system "git clone --single-branch --branch #{branch} --depth 1 #{url}"
end

clone_if_needed('webwork2', 'edfinity-docker', 'https://github.com/Edfinity/webwork2.git')
clone_if_needed('pg', 'master', 'https://github.com/Edfinity/pg.git')
clone_if_needed('MathJax', 'legacy-v2', 'https://github.com/mathjax/MathJax')

repo_tag = "778618701612.dkr.ecr.us-east-1.amazonaws.com/webwork2:#{options[:version]}"
local_tag = "edfinity/webwork2:#{options[:version]}"

cmd = "docker build -t #{local_tag} -t #{repo_tag} #{options[:clear_cache]} --platform linux/amd64 -f webwork2/Dockerfile ."
system cmd

if options[:push]
  puts "pushing #{repo_tag}"
  system "docker push '#{repo_tag}'"
end

system "docker history #{local_tag}"
